export const GET_AGREEMENTS_REQUEST = "GET_AGREEMENTS_REQUEST";
export const GET_AGREEMENTS_FAILURE = "GET_AGREEMENTS_FAILURE";
export const GET_AGREEMENTS_SUCCESS = "GET_AGREEMENTS_SUCCESS";

export const GET_AGREEMENT_REQUEST = "GET_AGREEMENT_REQUEST";
export const GET_AGREEMENT_FAILURE = "GET_AGREEMENT_FAILURE";
export const GET_AGREEMENT_SUCCESS = "GET_AGREEMENT_SUCCESS";

export const CREATE_AGREEMENT_REQUEST = "CREATE_AGREEMENT_REQUEST";
export const CREATE_AGREEMENT_FAILURE = "CREATE_AGREEMENT_FAILURE";
export const CREATE_AGREEMENT_SUCCESS = "CREATE_AGREEMENT_SUCCESS";
