export const GET_ENTITIES_REQUEST = "GET_ENTITIES_REQUEST";
export const GET_ENTITIES_FAILURE = "GET_ENTITIES_FAILURE";
export const GET_ENTITIES_SUCCESS = "GET_ENTITIES_SUCCESS";

export const GET_ENTITY_REQUEST = "GET_ENTITY_REQUEST";
export const GET_ENTITY_FAILURE = "GET_ENTITY_FAILURE";
export const GET_ENTITY_SUCCESS = "GET_ENTITY_SUCCESS";

export const CREATE_ENTITY_REQUEST = "CREATE_ENTITY_REQUEST";
export const CREATE_ENTITY_FAILURE = "CREATE_ENTITY_FAILURE";
export const CREATE_ENTITY_SUCCESS = "CREATE_ENTITY_SUCCESS";
