export const GET_HISTORIES_REQUEST = "GET_HISTORIES_REQUEST";
export const GET_HISTORIES_FAILURE = "GET_HISTORIES_FAILURE";
export const GET_HISTORIES_SUCCESS = "GET_HISTORIES_SUCCESS";

export const GET_HISTORY_REQUEST = "GET_HISTORY_REQUEST";
export const GET_HISTORY_FAILURE = "GET_HISTORY_FAILURE";
export const GET_HISTORY_SUCCESS = "GET_HISTORY_SUCCESS";

export const CREATE_HISTORY_REQUEST = "CREATE_HISTORY_REQUEST";
export const CREATE_HISTORY_FAILURE = "CREATE_HISTORY_FAILURE";
export const CREATE_HISTORY_SUCCESS = "CREATE_HISTORY_SUCCESS";

export const UPDATE_HISTORY_REQUEST = "UPDATE_HISTORY_REQUEST";
export const UPDATE_HISTORY_SUCCESS = "UPDATE_HISTORY_SUCCESS";
export const UPDATE_HISTORY_FAILURE = "UPDATE_HISTORY_FAILURE";
