export const GET_PATIENTS_REQUEST = "GET_PATIENTS_REQUEST";
export const GET_PATIENTS_FAILURE = "GET_PATIENTS_FAILURE";
export const GET_PATIENTS_SUCCESS = "GET_PATIENTS_SUCCESS";

export const GET_PATIENT_REQUEST = "GET_PATIENT_REQUEST";
export const GET_PATIENT_FAILURE = "GET_PATIENT_FAILURE";
export const GET_PATIENT_SUCCESS = "GET_PATIENT_SUCCESS";

export const UPDATE_PATIENT_REQUEST = "UPDATE_PATIENT_REQUEST";
export const UPDATE_PATIENT_FAILURE = "UPDATE_PATIENT_FAILURE";
export const UPDATE_PATIENT_SUCCESS = "UPDATE_PATIENT_SUCCESS";

export const CREATE_PATIENT_REQUEST = "CREATE_PATIENT_REQUEST";
export const CREATE_PATIENT_FAILURE = "CREATE_PATIENT_FAILURE";
export const CREATE_PATIENT_SUCCESS = "CREATE_PATIENT_SUCCESS";
