export const GET_SETTING_REQUEST = "GET_SETTING_REQUEST";
export const GET_SETTING_FAILURE = "GET_SETTING_FAILURE";
export const GET_SETTING_SUCCESS = "GET_SETTING_SUCCESS";

export const UPDATE_SETTING_REQUEST = "UPDATE_SETTING_REQUEST";
export const UPDATE_SETTING_FAILURE = "UPDATE_SETTING_FAILURE";
export const UPDATE_SETTING_SUCCESS = "UPDATE_SETTING_SUCCESS";
